[WIP]Search screen
AdamGlabicki/weather_aplication pull request #3
Opened 2022-08-02 11:28 UTC by AdamGlabicki

2022-08-08 10:07 UTC, andrzejplatek requested changes

2022-08-08 10:07 UTC, andrzejplatek commented on weather_aplication/MainViewController.swift
> +        //cityLabel.text = cityString
Staramy się nie zostawiać zakomentowanych rzeczy w kodzie

2022-08-08 10:07 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +        // Do any additional setup after loading the view.
Też niepotrzebny komentarz

2022-08-08 10:07 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +                }
Ten styl pętli nawiązuje trochę do C++, ale my używamy troszkę innej pętli for. Mianowicie zamiast robić _for i in range_ robimy _for result in results_, co od razu pozwala nam się dostać do poszczególnych elementów listy. Zauważ też że _self.cityNameArray = cityArray_ robisz w każdej iteracji pętli, taką rzecz raczej na koniec chcemy robić.

2022-08-08 10:07 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +                        self.decodeJson(jsonResult: jsonResult, completion: completion)
Dekodowanie jsonów zrobimy inaczej

2022-08-08 10:07 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +    func decodeJson(jsonResult: Any,completion: @escaping (_ result: [Location]?) -> Void) {
ta funkcja nie powinna przyjmować completion, ona powinna mieć za zadanie tylko jedną rzecz, to znaczy dekodowane jsona. Przyjmuje JSONA i zwraca zdecodowany obiekt.

2022-08-08 10:07 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +            make.leftMargin.rightMargin.bottomMargin.equalToSuperview()
nie musisz tutaj pisać margin, wystarczy left.right.bottom.equalToSuperview

2022-08-08 10:07 UTC, andrzejplatek commented on weather_aplication/MainViewController.swift
> +    init(city: String) {
Może nadaj temu controllerowi inną nazwę, żeby była skorelowana z tym co on faktycznie robi

2022-08-08 15:02 UTC, andrzejplatek requested changes

2022-08-08 15:02 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +                        completion(nil)
tak sobię myślę że nie ma co kilka razy pisać tego completion(nil), średnio czytelnie to wygląda. Czytelniej będzie jak nie będziesz dawał optionala w funkcji completion. Zresztą też nie musisz go wywoływać jak tam nie wpadnie w konkretnego case'a.

2022-08-08 15:02 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +            }
Zróbmy jakieś podstawowe mapowanie tych errorów. To znaczy jak wypadnie nam error to niech wyskoczy alert z treścią problemu i przyciskiem OK. Najprościej sobie zasymulować taki error jak wyłączysz połączenie internetowe.

2022-08-08 15:02 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +        session.dataTask(with: queryURL, completionHandler: { [self] data, response, error -> Void in
Zamiast tego musisz napisać coś innego, podsyłam ci artykuł w którym sobie doczytasz co to powinno być i dalczego. https://www.avanderlee.com/swift/weak-self/

2022-08-08 15:02 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +    func decodeJson(jsonResult: GeoDBJSON) -> [Location]? {
Nie powinieneś dawać w takiej funkcji optionala, zawsze da się coś zwrócić, chociażby pustą listę

2022-08-08 15:02 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +        if !datas.isEmpty{
tego sprawdzenia czy lista jest pusta nie musisz wykonywać, w najgorszym razie pętla for się nie wykona ani razu i zwróci się pusta lista.

2022-08-08 15:02 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +            make.leftMargin.rightMargin.equalToSuperview()
tutaj też możesz usunąć słowo Margin

2022-08-08 15:02 UTC, andrzejplatek commented on weather_aplication/SearchViewController.swift
> +        cityNamesTableView.reloadData()
To jest umieszczone w złym miejscu. Pomyśl i napisz mi gdzie i dlaczego to tam powinno być

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +    private let kSideMargin: CGFloat = 10
to chyba nie jest nigdzie używane

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +    private let kBottomMargin: CGFloat = 15
i to też

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +    private let kBottomMargin: CGFloat = 15
taka uwago-ciekawostka - przy używaniu SnapKita nie musisz używać `CGFloat`ów jako wartości constraintów, mogą to być też liczby typu `Int`, tak więc wystarczy wtedy pisać `private let kBottomMargin = 15` bez specyfikowania typu

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +    var cityNameArray: [String] = []
w zasadzie czemu to nie jest private?

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +        guard let cityName = cityNameTextfield.text else {return}
przed i po nawiasie klamrowym pisz spację `else { return }`

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +                guard let city = result.city else {break}
tutaj też klamerki do poprawy

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +                    } catch let eror {
literówka się wkradła w error 😄

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +                        guard let data = data else { return }
o tutaj na przykład nawiasy są elegancko 👀

2022-08-09 09:26 UTC, kacperZ commented on weather_aplication/SearchViewController.swift
> +        guard let text = cell?.textLabel?.text else {return}
nawiasy

2022-08-10 08:12 UTC, merged