[WIP]ClientAPI
AdamGlabicki/weather_aplication pull request #6
Opened 2022-08-19 07:25 UTC by AdamGlabicki

2022-08-19 10:32 UTC, andrzejplatek requested changes

2022-08-19 10:32 UTC, andrzejplatek commented on weatherAplication/Client/ClientAPI.swift
> +final class ClientAPI {
U nas jednak zawsze nazywamy tą klasę APIClient

2022-08-19 10:32 UTC, andrzejplatek commented on weatherAplication/Client/ClientAPI.swift
> +    func searchWeather(latitude: Double, longitude: Double, view: UIViewController, completion: @escaping (_ result: [WeatherData], _ date: String) -> Void) {
oj nie przekazujmy czegoś takiego jak view do APIClienta.

2022-08-19 10:32 UTC, andrzejplatek commented on weatherAplication/Client/ClientAPI.swift
> +            }
To powinno być zrobione w taki sposób, że funkcja jest oznaczona że może zwrócić error i zrobił handlowanie erroru dopiero w viewControllerze

2022-08-19 10:32 UTC, andrzejplatek commented on weatherAplication/Client/ClientAPI.swift
> +                    }
jak wyżej, tutaj powinien być jakiś _throw Error_

2022-08-19 10:32 UTC, andrzejplatek commented on weatherAplication/SearchView/SearchViewController.swift
> +    private let client = ClientAPI.sharedInstance
bardziej odpowiednia nazwa to apiClient

2022-08-19 14:34 UTC, andrzejplatek requested changes

2022-08-19 14:34 UTC, andrzejplatek commented on weatherAplication/ShowWeather/ShowWeatherViewController.swift
> +                self?.present(alert, animated: true)
zauważ że weatherData sugeruje nam że ta zmienna ma jakiś konkretny format danych- w tym przypadku to pewnie były by jakieś dane pogodowe, a zupełnie nie sugeruje że to może być enum z success i failure. Poza tym nie jest to też super czytelny. Myślę że lepszym rozwiązaniem jest oznaczenie funkcji searchWeather jako mogącej potencjalnie zfailować (poprzez nadanie jej atrybutu _throws_) i dopiero w tym miejscu zrobienie
do {
try ... 
} catch {
...
}

2022-08-19 14:34 UTC, andrzejplatek commented on weatherAplication/ShowWeather/ShowWeatherViewController.swift
> +        apiClient.searchWeather(latitude: latitude, longitude: longitude, completion: { [weak self] weatherData, date -> Void in
tak sobie myślę że ta część w sumie powinna być wykonana najszybciej jak to tylko możliwe, to znaczy w inicie. Nie chcemy czekać z requestem aż się widok załaduje, tylko wykonać go tak szybko jak mamy odpowiednie dane

2022-08-19 14:34 UTC, andrzejplatek commented on weatherAplication/ShowWeather/ShowWeatherViewController.swift
>      override func viewDidLoad() {
może to drobna rzecz ale funkcję viewDidLoad możesz przenieść poniżej inita. W taki sposób trochę łatwiej się to czyta bo funkcje są poukładane w kolejności ich wykonywania

2022-08-19 14:34 UTC, andrzejplatek commented on weatherAplication/Client/APIClient.swift
> +        return cityNames
tak naprawdę to się da zrobić w jednej linijce i używasz tego w tylko jednym miejscu, więc nie wiem czy jest sens robić na to oddzielną funkcję

2022-08-19 14:34 UTC, andrzejplatek commented on weatherAplication/Client/APIClient.swift
> +                guard let error = error else { return }
może by tak zrobić if let error = error, dzięki temu nie będziesz musiał tego guarda pisać

2022-08-22 09:06 UTC, andrzejplatek requested changes

2022-08-22 09:06 UTC, andrzejplatek commented on weatherAplication/ShowWeather/ShowWeatherViewController.swift
> +                case .failure(let error):
Ale tego case'a to wywal skoro już jest zrobiony error handling

2022-08-22 09:06 UTC, andrzejplatek commented on weatherAplication/Client/APIClient.swift
> +                completion(.failure(error))
tutaj powinien być throw zamiast completion

2022-08-22 09:06 UTC, andrzejplatek commented on weatherAplication/Client/APIClient.swift
> +                        completion(.failure(error))
tak samo, wszędzie zamiast completion(.failure) powinien być throw

2022-08-22 09:19 UTC, kacperZ commented on weatherAplication/Client/APIClient.swift
> +    private var kElementsToShow = 24
to w końcu zmienna czy stała? 😄

2022-08-22 09:19 UTC, kacperZ commented on weatherAplication/SearchView/SearchViewController.swift
> +            self.present(alert, animated: true)
ten self. chyba niepotrzebny?

2022-08-22 09:19 UTC, kacperZ commented on weatherAplication/ShowWeather/ShowWeatherViewController.swift
> +        self.longitude = data.longitude
i te selfy też raczej niepotrzebne

2022-08-22 09:19 UTC, kacperZ commented on weatherAplication/ShowWeather/ShowWeatherViewController.swift
> +            self.present(alert, animated: true)
👀

2022-08-22 11:32 UTC, andrzejplatek requested changes

2022-08-22 11:32 UTC, andrzejplatek commented on weatherAplication/Client/APIClient.swift
> +    func searchWeather(latitude: Double, longitude: Double, completion: @escaping (_ result: [WeatherData], _ date: String) -> Void, failure: @escaping ((WeatherError) -> Void)) throws {
jeśli dodajesz failure closure to już nie trzeba dodawać _throws_ do funkcji

2022-08-22 11:32 UTC, andrzejplatek commented on weatherAplication/SearchView/SearchViewController.swift
> +        }
ten catch jednak niepotrzebny

2022-08-22 11:38 UTC, andrzejplatek approved these changes

2022-08-23 08:06 UTC, merged